site_name: SDE Prep A2Z

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.math
    - navigation.footer
    - navigation.sections
    - navigation.instant  # no full page reloads (smooth UX)
    - navigation.tracking # highlights active section in sidebar
    - search.highlight
    - search.share
    - search.suggest
  
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: dracula
      toggle:
        icon: material/ghost
        name: Dracula Mode

    - scheme: neon
      primary: lime
      accent: pink
      toggle:
        icon: material/lightbulb-on-outline
        name: Neon Pulse Mode

    - scheme: cyberpunk
      primary: yellow
      accent: light blue
      toggle:
        icon: material/robot
        name: Cyberpunk Mode

  font:
    text: "D2Coding Ligature"
    code: "JetBrainsMono Nerd Font"

nav:
  - Home: index.md
  - DSA:
      - Arrays: DSAyy/arrays.md
      - Dynamic Programming: DSAyy/dp.md
      - Graphs: DSAyy/graph.md
      - Trees: DSAyy/trees.md
      - Two Pointers: DSAyy/TwoPointers.md
      - Linked Lists: DSAyy/LinkedList.md
      - Stacks and Queues: DSAyy/stacks_queues.md
      - Strings: DSAyy/Strings.md
      - Maths: DSAyy/Maths.md
      - Bit Manipulation: DSAyy/bit_manipulation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - awesome-pages
  - glightbox


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your/repo
  favicon: images/favicon.ico
  font:
    text: Roboto
    code: Fira Code

extra_css:
  - styles/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css
  - styles/fonts.css   # Custom font declarations
extra_javascript:
  # 1) KaTeX core
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.js
  # 2) KaTeX auto-render extension
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js
  # 3) Our PJAX-aware render hook
  - javascripts/katex-render.js
