site_name: SDE Prep A2Z

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.sections
    - navigation.instant  # no full page reloads (smooth UX)
    - navigation.tracking # highlights active section in sidebar
    - search.highlight
    - search.share
    - search.suggest
  
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: dracula
    toggle:
      icon: material/ghost
      name: Dracula Mode


nav:
  - Home: index.md
  - DSA:
      - Arrays: DSAyy/arrays.md
      - Dynamic Programming: DSAyy/dp.md
      - Graphs: DSAyy/graph.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - awesome-pages
  - glightbox


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your/repo
  favicon: images/favicon.ico
  font:
    text: Roboto
    code: Fira Code

extra_css:
  - styles/custom.css
